### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by bimintelligence** [rorlandoc/vtkFromOdb#1]
Hi, I have tried to input the .odb file.
It just shows "File not found", and I have put it in the same level and in the root of E.

![image](https://github.com/rorlandoc/vtkFromOdb/assets/73410751/be9f75b6-6bf1-4517-9a04-18cb27d1ff0a)
![image](https://github.com/rorlandoc/vtkFromOdb/assets/73410751/99537246-77a1-41ee-9fd9-78452ea8af45)

![image](https://github.com/rorlandoc/vtkFromOdb/assets/73410751/e96ca2d5-ebbd-4399-879e-d211a81f8cd7)

**Comment by rorlandoc** [comment]
Hi @SHAWNZHANGSH, thanks for reporting this. There was a bug when handling the odb file extension whenever the argument was provided with the extension. I pushed a fix in [c6fe18d](https://github.com/rorlandoc/vtkFromOdb/commit/c6fe18d7d76c101a13ec2ffa75c25f0c89323cf9) in the `dev` branch. Could you please see if that fixes the issue for you?

Also, right now, the scripts can only handle odb files in the same directory as the python scripts. Whenever I get a change I'll extend this to support arbitrary working directories
